#!/usr/bin/env ruby

forge "https://forgeapi.puppetlabs.com"

mod 'puppetlabs-stdlib', '4.13.1'
mod 'puppetlabs-firewall', '1.11.0'
mod 'cmc-ipa',
  :git => 'https://github.com/Fabian1976/puppet-ipa.git',
  :ref => '1.3.0'
